# SPDX-License-Identifier: Apache-2.0
#
# bin2c.cmake - turn a binary file into a C array.
#
#   cmake -DIN=<file> -DOUT=<file.c> -DSYM=<name> -P bin2c.cmake
#
# A script rather than a tool, so a checkout needs nothing built before
# it can embed data, and CMake rather than xxd because this has to work
# wherever the build does.
#
# The length is emitted beside the array. A caller that took sizeof()
# instead would be right until the day someone declared the array
# `extern` in a header, at which point sizeof silently becomes wrong --
# which is a mistake this tree has made before with a different array.

if(NOT DEFINED IN OR NOT DEFINED OUT OR NOT DEFINED SYM)
    message(FATAL_ERROR "bin2c: need -DIN=, -DOUT= and -DSYM=")
endif()

file(READ "${IN}" _hex HEX)
string(LENGTH "${_hex}" _chars)
math(EXPR _len "${_chars} / 2")

# 0xNN, per byte, wrapped so no line is pathological for a compiler.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _body "${_hex}")
string(REGEX REPLACE "((0x..,){16})" "\\1\n\t" _body "${_body}")

file(WRITE "${OUT}"
"/* Generated by bin2c.cmake from ${IN}. Do not edit. */\n"
"const unsigned char ${SYM}[] = {\n\t${_body}\n};\n"
"const unsigned int ${SYM}_len = ${_len}u;\n")

message(STATUS "bin2c: ${IN} -> ${OUT} (${_len} bytes)")
