/* SPDX-License-Identifier: Apache-2.0 */
/*
 * alu.c - the e200z7 frontend's integer instructions, as a compiler
 * emits them, against values computed elsewhere.
 *
 * **Compiled C, and that is the point.** isatest.S exercises what
 * someone thought to write, in VLE; this is classic Book E, which GCC
 * generates and nothing else in the tree does, in the forms a compiler
 * reaches for without being asked: addc/adde and subfc/subfe chains for
 * 64-bit arithmetic, srawi followed by addze for a signed divide by a
 * power of two (which is XER[CA] or it is nothing), rlwinm and rlwimi
 * for every field access, isel, the update forms in loops, lmw/stmw in
 * prologues, bctr through a jump table and crxor before a variadic
 * call.
 *
 * The expected values are **not** computed by this program: they are in
 * alu_want.h, generated by alu_want.py from Python's integers. The
 * inputs below are repeated there.
 *
 * Everything is `volatile` or noinline so that the compiler has to emit
 * the instruction rather than the answer.
 */
#include "alu_want.h"
#include "ppc_clock.h"

#include <stdarg.h>

typedef unsigned int u32;
typedef int s32;
typedef unsigned long long u64;
typedef long long s64;
typedef unsigned short u16;
typedef short s16;
typedef unsigned char u8;
typedef signed char s8;

#define UART (*(volatile unsigned char *)0x10000000u)
#define NOINLINE __attribute__((noinline))

static void pc_(char c)
{
    UART = (unsigned char)c;
}
static void ps_(const char *s)
{
    while (*s) {
        pc_(*s++);
    }
}
static void phex(u32 v)
{
    int i;

    for (i = 28; i >= 0; i -= 4) {
        pc_("0123456789abcdef"[(v >> i) & 0xFu]);
    }
}

volatile u32 va = 0xDEADBEEFu;
volatile u32 vb = 7u;
volatile u32 vc = 0x80000000u;
volatile u32 vd = 0x12345678u;
volatile s32 sa = -1000003;
volatile s32 sb = 17;
volatile u64 qa = 0xFEDCBA98F6543210ull;
volatile u64 qb = 0x0123456789ABCDEFull;
volatile u32 vn = 13u;
volatile u32 vm = 45u;

static u32 g_fail;
static u32 g_checks;

static NOINLINE void check(const char *name, u32 got, u32 want)
{
    g_checks++;
    if (got != want) {
        g_fail++;
        ps_("FAIL ");
        ps_(name);
        ps_(" got ");
        phex(got);
        ps_(" want ");
        phex(want);
        pc_('\n');
    }
}

#define CHECK(name, expr) check(#name, (u32)(expr), WANT_##name)
#define CHECK64(name, expr)                                                    \
    do {                                                                       \
        const u64 v_ = (u64)(expr);                                            \
        check(#name "_HI", (u32)(v_ >> 32), WANT_##name##_HI);                 \
        check(#name "_LO", (u32)v_, WANT_##name##_LO);                         \
    } while (0)

static NOINLINE u32 rotl(u32 x, u32 n)
{
    return (x << (n & 31u)) | (x >> ((32u - n) & 31u));
}

static NOINLINE u32 fib(u32 n)
{
    return (n < 2u) ? n : fib(n - 1u) + fib(n - 2u);
}

static u32 op_add(u32 a)
{
    return a + 3u;
}
static u32 op_mul(u32 a)
{
    return a * 5u;
}
static u32 op_xor(u32 a)
{
    return a ^ 0x5A5A5A5Au;
}
static u32 op_shr(u32 a)
{
    return a >> 2;
}
static u32 (*const volatile g_ops[4])(u32) = {op_add, op_mul, op_xor, op_shr};

static NOINLINE u32 sw(u32 i)
{
    switch (i) {
    case 0:
        return 11u;
    case 1:
        return 23u;
    case 2:
        return 5u;
    case 3:
        return 77u;
    case 4:
        return 42u;
    case 5:
        return 9u;
    case 6:
        return 100u;
    case 7:
        return 1u;
    default:
        return 3u;
    }
}

static NOINLINE u32 vsum(u32 n, ...)
{
    va_list ap;
    u32 s = 0u;
    u32 i;

    va_start(ap, n);
    for (i = 0u; i < n; i++) {
        s += va_arg(ap, u32);
    }
    va_end(ap);
    return s;
}

struct __attribute__((packed)) odd {
    u8 pad;
    u32 w;
    u8 pad2[2];
    u16 h;
};

static u8 g_b[64];
static u16 g_h[32];
static u32 g_w[16];
static u8 g_buf[16];

int main(void)
{
    u32 i;
    u32 acc;

    /* --- 64-bit arithmetic: the carry chains ----------------------- */
    CHECK64(ADD64, qa + qb);
    CHECK64(SUB64, qa - qb);
    CHECK64(SUB64R, qb - qa);
    CHECK64(MUL64, qa * qb);
    CHECK64(SHR64, qa >> vn);
    CHECK64(SHL64, qa << vn);
    CHECK64(SAR64, (s64)qa >> vn);
    CHECK64(SHR64W, qa >> vm);
    CHECK64(SHL64W, qa << vm);
    CHECK64(SAR64W, (s64)qa >> vm);
    CHECK(CMP64, (qa > qb ? 1u : 0u) | ((s64)qa > (s64)qb ? 2u : 0u) |
                     (qa == qb ? 4u : 0u) | ((s64)qa < 0 ? 8u : 0u));
    CHECK64(NEG64, -qb);

    /* --- divide, and the divide the compiler does not emit --------- */
    CHECK(UDIV, va / vb);
    CHECK(UMOD, va % vb);
    CHECK(SDIV, sa / sb);
    CHECK(SMOD, sa % sb);
    CHECK(SDIV8, sa / 8);   /* srawi; addze */
    CHECK(SMOD8, sa % 8);
    CHECK(SAR3, sa >> 3);
    CHECK(SDIVNEG, sa / -sb);

    /* --- rotates and fields ---------------------------------------- */
    CHECK(ROTL, rotl(va, vn));
    CHECK(ROTR, rotl(va, 32u - vn));
    CHECK(EXTRACT, (va >> 5) & 0x3FFu);
    CHECK(INSERT, (vd & ~0x00FFF000u) | ((va << 12) & 0x00FFF000u));
    CHECK(CLZ, (u32)__builtin_clz(vd) + ((u32)__builtin_clz(vb) << 8) +
                   ((u32)__builtin_clz(vc) << 16));
    CHECK(EXTSB, (s32)(s8)va);
    CHECK(EXTSH, (s32)(s16)va);
    CHECK(BSWAP, __builtin_bswap32(va));
    CHECK(BSWAP16, __builtin_bswap16((u16)vd));

    /* --- selects and compares into values --------------------------- */
    CHECK(UMAX, va > vd ? va : vd);
    CHECK(SMAX, (s32)va > (s32)vd ? (s32)va : (s32)vd);
    CHECK(SMIN, (s32)va < (s32)vd ? (s32)va : (s32)vd);
    CHECK(MULHW, (s32)(((s64)sa * (s64)sb) >> 32));
    CHECK(MULHWU, (u32)(((u64)va * (u64)vd) >> 32));
    CHECK(MULHWS, (s32)(((s64)(s32)va * (s64)(s32)vd) >> 32));
    CHECK(MULLI, sa * 1000);
    CHECK(NEG, -sa);
    CHECK(ABS, sa < 0 ? -sa : sa);
    CHECK(LOGIC, ~(va & vd) ^ (va & ~vd) ^ (va | ~vd) ^ ~(va ^ vd) ^ ~(va | vd));
    CHECK(SETCC, (va == vd ? 1u : 0u) | (va != 0u ? 2u : 0u) | (sa < sb ? 4u : 0u) |
                     (va < vd ? 8u : 0u) | ((s32)va < (s32)vd ? 16u : 0u) |
                     (sa <= -1000003 ? 32u : 0u) | (vc > 0x7FFFFFFFu ? 64u : 0u) |
                     ((s32)vc >= 0 ? 128u : 0u));

    /* --- a 96-bit add, the carries by comparison -------------------- */
    {
        const u32 x0 = vc, x1 = vd, x2 = va;
        const u32 y0 = va, y1 = va, y2 = vc;
        const u32 z0 = x0 + y0;
        const u32 c0 = z0 < x0;
        const u32 t1 = x1 + y1;
        const u32 z1 = t1 + c0;
        const u32 c1 = (t1 < x1) | (z1 < t1);
        const u32 z2 = x2 + y2 + c1;

        CHECK(ADD96_2, z2);
        CHECK(ADD96_1, z1);
        CHECK(ADD96_0, z0);
    }

    /* --- memory ------------------------------------------------------ */
    for (i = 0u; i < 64u; i++) {
        g_b[i] = (u8)(i * 37u + 11u);
    }
    for (i = 0u; i < 32u; i++) {
        g_h[i] = (u16)(i * 2749u + 5u);
    }
    for (i = 0u; i < 16u; i++) {
        g_w[i] = i * 0x9E3779B1u + va;
    }
    {
        u32 sum = 0u;
        s32 ssum = 0;

        for (i = 0u; i < 64u; i++) {
            sum += g_b[i];
            ssum += (s8)g_b[i];
        }
        CHECK(SUMB, sum);
        CHECK(SUMSB, ssum);
        sum = 0u;
        ssum = 0;
        for (i = 0u; i < 32u; i++) {
            sum += g_h[i];
            ssum += (s16)g_h[i];
        }
        CHECK(SUMH, sum);
        CHECK(SUMSH, ssum);
        acc = 0u;
        for (i = 0u; i < 16u; i++) {
            acc = rotl(acc, 5u) ^ g_w[i];
        }
        CHECK(XORW, acc);
    }
    {
        /* Big-endian: the most significant byte is at the lowest address. */
        volatile u32 word = 0x11223344u;
        const volatile u8 *const p = (const volatile u8 *)&word;

        CHECK(ENDIAN, (u32)p[0] | ((u32)p[1] << 8) | ((u32)p[2] << 16) |
                          ((u32)p[3] << 24));
    }
    {
        const volatile struct odd *o;
        volatile u32 *aligned;

        for (i = 0u; i < 16u; i++) {
            g_buf[i] = (u8)(i * 29u + 3u);
        }
        o = (const volatile struct odd *)(void *)g_buf;
        CHECK(UNALIGNED, o->w);
        CHECK(UNALIGNEDH, o->h);
        aligned = (volatile u32 *)(void *)&g_buf[4];
        CHECK(LWBRX, __builtin_bswap32(*aligned));
    }

    /* --- control flow ------------------------------------------------ */
    CHECK(FIB, fib(20u));
    acc = vd;
    for (i = 0u; i < 12u; i++) {
        acc = g_ops[i & 3u](acc);
    }
    CHECK(FNPTR, acc);
    acc = 0u;
    for (i = 0u; i < 10u; i++) {
        acc += sw(i) * (i + 1u);
    }
    CHECK(SWITCH, acc);
    CHECK(VARARGS, vsum(12u, 1u, 2u, 3u, 4u, 5u, 6u, 7u, 8u, 9u, 10u, 11u, 12u));
    {
        u32 n = 27u;
        u32 steps = 0u;

        while (n != 1u) {
            n = ((n & 1u) == 0u) ? n / 2u : 3u * n + 1u;
            steps++;
        }
        CHECK(COLLATZ, steps);
    }

    /*
     * The terminator, and the count: a run that printed this executed
     * every check above, which "no FAIL line" alone does not say.
     */
    ps_("PPC-ALU-END checks=");
    phex(g_checks);
    ps_(" fails=");
    phex(g_fail);
    ps_(ppc_dec_ticks != 0u ? " ticked\n" : " NO-TICK\n");
    return (int)g_fail;
}
